const stages=[["01","Intent","Agent requests a service","▤"],["02","Quote","Get price and allowed scope","⌘"],["03","Authority","Verify policy and limits","⬡"],["04","Settlement","USDC transaction on Base","≋"],["05","Execution","Service runs in boundary","</>"],["06","Observation","Independent verification","◉"],["07","Proof","Get verifiable evidence","#"]];
let currentProof=null;
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const short=(v,n=20)=>{v=String(v??"");return v.length>n?v.slice(0,n)+"…":v};
function draw(mode="idle"){ $("#timeline").innerHTML=stages.map((s,i)=>{let c="step";if(mode==="ok")c+=" pass";if(mode==="deny"){if(i<2)c+=" pass";else if(i===2)c+=" denied"}return '<article class="'+c+'"><div class="step-icon">'+s[3]+'</div><small>['+s[0]+']</small><b>'+s[1]+'</b><p>'+s[2]+'</p></article>'}).join("")} draw();
async function run(amount){try{const r=await fetch("/api/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({amount_atomic:amount,document:"Autonomous agents can purchase digital services. AgentPay Proof constrains payment authority and independently verifies the outcome. Evidence should not depend on the purchasing agent's own claims."})});const d=await r.json();if(!r.ok)throw new Error(d.error||"request failed");currentProof=d.proof;const denied=d.status==="DENIED";draw(denied?"deny":"ok");const list=$("#activity-list");const row=document.createElement("p");row.innerHTML='<i class="'+(denied?"bad":"ok")+'"></i><b>AgentPay Demo</b><em>'+(denied?"Denied (policy)":"Verified")+'</em><span>'+(denied?"—":"0.25 USDC")+'</span><small>now</small>';list.prepend(row);while(list.children.length>5)list.lastElementChild.remove();if(!denied)openEvidence()}catch(e){console.error(e)}}
function openEvidence(){if(!currentProof)return;const p=currentProof,rows=[["Intent",p.intent?.intent_id],["Quote",p.quote?.quote_id],["Authority",p.authority?.decision],["Settlement",p.settlement?.transaction_hash],["Execution",p.result?.result_digest],["Observation",p.observation?.observer_id],["Proof",p.proof_hash]];$("#evidence-grid").innerHTML=rows.filter(x=>x[1]).map(x=>'<article><small>'+esc(x[0])+'</small><div>'+esc(short(x[1],22))+'</div></article>').join("");$("#evidence-json").textContent=JSON.stringify(p,null,2);$("#evidence-dialog").showModal()}
$("#run-ok").onclick=()=>run(250000);$("#explore").onclick=()=>document.querySelector(".services").animate([{boxShadow:"0 0 0 rgba(21,151,255,0)"},{boxShadow:"0 0 36px rgba(21,151,255,.35)"},{boxShadow:"0 0 0 rgba(21,151,255,0)"}],{duration:900});
(()=>{
 const c=$("#scene"),x=c.getContext("2d"),parts=[],stars=[];let w,h,dpr=1,start=performance.now();
 function rnd(i){const n=Math.sin(i*991.7)*43758.5453;return n-Math.floor(n)}
 function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;c.style.width=w+"px";c.style.height=h+"px";x.setTransform(dpr,0,0,dpr,0,0);parts.length=0;stars.length=0;for(let i=0;i<220;i++)parts.push({b:rnd(i)*(w+300)-150,y:(rnd(i+80)-.5)*120,s:20+rnd(i+160)*95,z:.4+rnd(i+240)*1.4,p:rnd(i+320)*6.28});for(let i=0;i<420;i++)stars.push({x:rnd(i+600)*w,y:rnd(i+900)*h*.78,a:.12+rnd(i+1100)*.45,z:.4+rnd(i+1300)*1.4})}
 function riverY(px,t,l=0){return h*.43+Math.sin(px*.006+t*.00032)*44+Math.sin(px*.013-t*.00018)*16+l}
 function frame(now){x.clearRect(0,0,w,h);
  const bg=x.createLinearGradient(0,0,0,h);bg.addColorStop(0,"#07131f");bg.addColorStop(1,"#030911");x.fillStyle=bg;x.fillRect(0,0,w,h);
  // digital terrain
  for(let k=0;k<7;k++){x.beginPath();for(let px=180;px<w;px+=14){let y=h*.34+Math.sin(px*.007+k)*18+Math.sin(px*.021-k*.7)*6+k*12;if(px===180)x.moveTo(px,y);else x.lineTo(px,y)}x.strokeStyle="rgba(46,111,166,"+(0.06+k*.008)+")";x.lineWidth=.8;x.stroke()}
  for(const s of stars){x.fillStyle="rgba(50,160,255,"+s.a+")";x.fillRect(s.x,s.y,s.z,s.z)}
  for(let k=-3;k<=3;k++){x.beginPath();for(let px=180;px<w+40;px+=10){let y=riverY(px,now,k*9);if(px===180)x.moveTo(px,y);else x.lineTo(px,y)}x.strokeStyle=k===0?"rgba(220,245,255,.75)":"rgba(28,145,255,"+(0.16-Math.abs(k)*.018)+")";x.lineWidth=k===0?2.2:1;x.stroke()}
  const elapsed=(now-start)/1000;for(const p of parts){const span=w+300,px=((p.b+elapsed*p.s+150)%span)-150,py=riverY(px,now,p.y*.35+Math.sin(elapsed+p.p)*7);x.fillStyle=p.z>1.1?"rgba(225,246,255,.78)":"rgba(29,145,255,.55)";x.fillRect(px,py,p.z*1.7,p.z*1.7)}
  requestAnimationFrame(frame)}
 addEventListener("resize",resize,{passive:true});resize();requestAnimationFrame(frame)
})();